[package]
name = "xap-specs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
binrw = "0.11.1"
bitflags = "1.3"
flate2 = "1.0"
log = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
deser-hjson = "1"
serde_with = "2"
thiserror = "1.0"
ts-rs = { git = "https://github.com/Aleph-Alpha/ts-rs", branch = "main", features = [
    "serde-compat",
    "uuid-impl",
] }
uuid = { version = "1.2.1", features = ["serde", "v4"] }

[dev-dependencies]
similar-asserts = "1.4.2"
